# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout (historial completo para Sentry)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Setup Node + cache npm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3) Instalar dependencias (ci -> install si no hay lockfile)
      - name: Install deps
        env:
          NODE_ENV: development
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci (lockfile present)"
            npm ci --no-audit --no-fund
          else
            echo "package-lock.json not found, falling back to npm install"
            npm install --no-audit --no-fund
          fi

      # 4) Generar Prisma Client
      - name: Generate Prisma
        run: npx prisma generate

      # 5) Lint
      - name: Lint
        run: npm run lint

      # 6) Test
      - name: Test
        env:
          NODE_ENV: test
          JWT_SECRET: testsecret
          JWT_ISSUER: myapi
          JWT_AUDIENCE: myapi-clients
        run: npm test -- --runInBand

      # 7) Build
      - name: Build
        run: npm run build

      # 8) Sentry release (solo main)
      - name: Sentry release
        if: github.ref == 'refs/heads/main'
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
