# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repo (full history helps Sentry associate commits)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Install pnpm CLI
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # 3) Setup Node and pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 4) Install dependencies (dev deps included)
      - name: Install deps
        run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      # 5) Generate Prisma Client
      - name: Generate Prisma
        run: pnpm prisma generate

      # 6) Lint
      - name: Lint
        run: pnpm lint

      # 7) Test
      - name: Test
        env:
          NODE_ENV: test
          JWT_SECRET: testsecret
          JWT_ISSUER: myapi
          JWT_AUDIENCE: myapi-clients
        run: pnpm test -- --runInBand

      # 8) Build (dist/)
      - name: Build
        run: pnpm build

      # 9) Sentry release (only on main)
      - name: Sentry release
        if: github.ref == 'refs/heads/main'
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          # by default this uses the current commit SHA as the release version
          # and associates commits thanks to checkout fetch-depth: 0
